model_list:
  - model_name: anthropic/MiniMax-M2.7
    litellm_params:
      model: anthropic/MiniMax-M2.7
      api_base: "https://api.minimaxi.com/anthropic"
      api_key: "sk-cp-bdaf8sYn6w87XxOCStGtMDQphNK5raath68ftqFVK6gSQ-1SxOZXnaO8KO0UaSCDjJla1XwxahrxA-sr7VdQiULybYxFI65wITq25a1zq7gfl68i44aWkdc"
  - model_name: anthropic/MiniMax-M2.7
    litellm_params:
      model: anthropic/MiniMax-M2.7
      api_base: "https://api.minimaxi.com/anthropic"
      api_key: "sk-cp-bdaf8sYn6w87XxOCStGtMDQphNK5raath68ftqFVK6gSQ-1SxOZXnaO8KO0UaSCDjJla1XwxahrxA-sr7VdQiULybYxFI65wITq25a1zq7gfl68i44aWkdc"
litellm_settings:
  drop_params: true # 忽略 Minimax 不支援的 Anthropic 專屬參數
  set_completed_by: true
