model_list:
  - model_name: anthropic/MiniMax-M2.7
    litellm_params:
      model: anthropic/MiniMax-M2.7
      api_base: "https://api.minimaxi.com/anthropic"
      api_key: "os.environ/MINIMAX_API_KEY"
  - model_name: claude-3-5-sonnet-20241022
    litellm_params:
      model: anthropic/MiniMax-M2.7
      api_base: "https://api.minimaxi.com/anthropic"
      api_key: "os.environ/MINIMAX_API_KEY"
litellm_settings:
  drop_params: true
