"""
Prometheus metrics definitions for Voice AI Pipeline.

All metrics follow the OpenMetrics format and include appropriate labels
for multi-instance support in the future.
"""

from prometheus_client import Counter, Histogram, Gauge

# ============================================================================
# Latency Metrics (Histograms)
# ============================================================================

# VAD Latency: Time from last speech to VAD detection of silence
vad_latency = Histogram(
    "vad_latency_seconds",
    "VAD detection latency - time from last speech to silence detection",
    buckets=[0.1, 0.25, 0.5, 0.75, 1.0, 1.5, 2.0, 3.0, 5.0, 10.0],
    labelnames=["component", "model"],
)

# ASR Latency: Time from audio end to text output
asr_latency = Histogram(
    "asr_latency_seconds",
    "ASR processing latency - time from audio end to text output",
    buckets=[0.1, 0.25, 0.5, 0.75, 1.0, 1.5, 2.0, 3.0, 5.0, 10.0],
    labelnames=["component", "model"],
)

# RAG Retrieval Latency
rag_retrieval_seconds = Histogram(
    "rag_retrieval_seconds",
    "RAG knowledge base retrieval latency",
    buckets=[0.01, 0.025, 0.05, 0.1, 0.25, 0.5, 1.0, 2.5, 5.0],
    labelnames=["component", "index_name"],
)

# LLM Time to First Token
llm_ttft = Histogram(
    "llm_ttft_seconds",
    "LLM Time to First Token - time to generate first token",
    buckets=[0.1, 0.25, 0.5, 0.75, 1.0, 1.5, 2.0, 3.0, 5.0, 10.0],
    labelnames=["component", "model"],
)

# TTS Time to First Byte
tts_ttfb = Histogram(
    "tts_ttfb_seconds",
    "TTS Time to First Byte - time from text to first audio output",
    buckets=[0.05, 0.1, 0.25, 0.5, 0.75, 1.0, 1.5, 2.0],
    labelnames=["component", "model"],
)

# End-to-End Latency: User speaks to hearing response
e2e_latency = Histogram(
    "e2e_latency_seconds",
    "End-to-end latency - from user stops speaking to hearing response",
    buckets=[0.5, 0.75, 1.0, 1.25, 1.5, 2.0, 2.5, 3.0, 5.0, 10.0],
    labelnames=["component"],
)

# Streaming chunk latency
streaming_chunk_latency = Histogram(
    "streaming_chunk_latency_seconds",
    "Latency for each streaming chunk",
    buckets=[0.01, 0.025, 0.05, 0.075, 0.1, 0.25, 0.5],
    labelnames=["component", "stream_type"],  # stream_type: "llm_tokens" | "tts_audio"
)

# ============================================================================
# Throughput Metrics (Counters)
# ============================================================================

audio_chunks_total = Counter(
    "audio_chunks_total",
    "Total number of audio chunks received",
    labelnames=["component", "session_id"],
)

utterances_total = Counter(
    "utterances_total",
    "Total number of utterances processed",
    labelnames=["component", "session_id"],
)

asr_results_total = Counter(
    "asr_results_total",
    "Total number of ASR results (partial + final)",
    labelnames=["component", "model", "result_type"],  # result_type: "partial" | "final"
)

llm_tokens_total = Counter(
    "llm_tokens_total",
    "Total number of tokens generated by LLM",
    labelnames=["component", "model", "session_id"],
)

tts_chunks_total = Counter(
    "tts_chunks_total",
    "Total number of TTS audio chunks generated",
    labelnames=["component", "model", "session_id"],
)

ws_connections_total = Counter(
    "ws_connections_total",
    "Total number of WebSocket connections",
    labelnames=["component", "status"],  # status: "connected" | "disconnected"
)

ws_messages_total = Counter(
    "ws_messages_total",
    "Total number of WebSocket messages",
    labelnames=["component", "direction", "message_type"],
    # direction: "sent" | "received"
    # message_type: "audio" | "text" | "control"
)

# ============================================================================
# Streaming Metrics (Gauges - real-time values)
# ============================================================================

llm_tokens_per_second = Gauge(
    "llm_tokens_per_second",
    "Current LLM token generation rate",
    labelnames=["component", "model"],
)

tts_audio_bytes_per_second = Gauge(
    "tts_audio_bytes_per_second",
    "Current TTS audio generation rate",
    labelnames=["component", "model"],
)

audio_buffer_size_bytes = Gauge(
    "audio_buffer_size_bytes",
    "Current audio buffer size in bytes",
    labelnames=["component", "session_id"],
)

active_sessions = Gauge(
    "active_sessions",
    "Number of currently active sessions",
    labelnames=["component"],
)

# ============================================================================
# Error Metrics (Counters)
# ============================================================================

errors_total = Counter(
    "errors_total",
    "Total number of errors",
    labelnames=["component", "error_type", "model"],
)

asr_failures_total = Counter(
    "asr_failures_total",
    "Total number of ASR failures",
    labelnames=["component", "model", "error_type"],
)

llm_failures_total = Counter(
    "llm_failures_total",
    "Total number of LLM failures",
    labelnames=["component", "model", "error_type"],
)

tts_failures_total = Counter(
    "tts_failures_total",
    "Total number of TTS failures",
    labelnames=["component", "model", "error_type"],
)
